version: "3"

services:
  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    build: ../src/AltenCode.Api
    links:
      - rabbitmq
      - mongo
    ports:
      - '5000:5000'

  vehicles-service:
    build: ../src/AltenCode.Services.Vehicles
    links:
      - rabbitmq
      - mongo
    ports:
      - '5050:5050'

  alten-web:
    container_name: alten.web
    build: ../src/AltenCode.Web
    volumes:
      - '../src/AltenCode.Web:/app'
    ports:
      - '4200:4200'
    command: >
        bash -c "npm uninstall --save node-sass && npm install --save node-sass && npm rebuild node-sass --force && npm install && ng serve --host 0.0.0.0 --port 4200"

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'